language: python
cache: pip
jobs:
  include:
  - stage: Style Checking
    python: '3.6'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    - pip install black
    script: black setup.py tests/ tgcli/ -l 79
  - stage: Testing (Python 3.5)
    python: '3.5'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    script: pytest
  - stage: Testing (Python 3.6)
    python: '3.6'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    script: pytest
  - stage: Covering / Deploy
    python: '3.6'
    install:
    - pip install -r requirements.txt
    - pip install -r dev.requirements.txt
    script:
    - pytest --cov tgcli tests/
    - codecov
    deploy:
      provider: pypi
      user: erayerdin
      password:
        secure: "TWXBDAovoK1lrm7kHYAmdtcLYX6k4rwXDNyi20oNZSNXsLwafLbyX1a/OUmQwBBEJ0epDE2nkTB9fyfMErMw7V900Cf9WXj972XDApoDnLV+aby8O3WsEaO8tlQnCDTXBG03G6uf+v6yQmLd0lthUQJTNw2n3kOgADjATODFzpqBO+77bf2gKY7qXSqIF0g6KIkpKTPwh4X8ogrR7HjV/lGuOwb537HlIMSJLlXTqVXSShuQoBKIyIqBCxmlWsJsmj43UK4K8dT06uH3O7DxdinCNOHqATqO2IgbKCIqAMgxG9YPPdjhYJHGtKOWqnPYCyGH4QqsqgXkmmCRfDvAC8Lig8WMaEJXmv7A4AaMEMTD0aR5e7+1NRPhEGLlvE/p13ikHlhSw6vMDIKRGY/sSmF4Ru6BytfxmFVvNLl56XsZ6F55CNeEZJJRNNsFjtIrqsWJgwl3UZlZLA0Mn/7oFI3laCrhjwluNF5d+wtSgubmo3149tVTQgDukRbcOQhq0wsG357Q4DcY3YNoOU3PIxzubPGkThkYwlfKm2Y2X4psrA3+Hh28oqmxylpMJKoC3mu/TXlJ4yXISrk+lJkaeHUiKmXdCeElbN7Ht5WOXOvzD0B6afEKZz5En2r01K/OhQ2YeHN+rPkkGC+XTCEPOvv7P/sVHTknK/NrkouqKQY="
      on:
        tags: true
